import { NextRequest, NextResponse } from "next/server";
import { google } from "googleapis";
import { googleWorkspaceWriteBlockedSource, isGoogleWorkspaceAuthError } from "@/lib/api/google-workspace-error";
import { getAuth } from "@/lib/sheets/sheets-real";
import { appendSwiMemoryLog } from "@/lib/google/audit-log";
import { getTemplateByType } from "@/lib/document";
import type { DocumentType } from "@/lib/document";

export const runtime = "nodejs";

type SavePayload = {
  id?: string;
  type?: DocumentType;
  title?: string;
  content?: string;
  letterNumber?: string;
};

function text(value: unknown) {
  return String(value ?? "").trim();
}

function safeTitle(value: string) {
  return value.replace(/[\\/:*?"<>|]+/g, "-").replace(/\s+/g, " ").trim().slice(0, 140);
}

function isDocumentType(value: string): value is DocumentType {
  return Boolean(getTemplateByType(value as DocumentType));
}

function buildGoogleDocText(payload: Required<Pick<SavePayload, "title" | "content">> & SavePayload) {
  const lines = [
    payload.title,
    payload.letterNumber ? `Nomor: ${payload.letterNumber}` : "Status: Draft systemswi",
    "",
    payload.content,
    "",
    "---",
    `Generated by systemswi at ${new Date().toISOString()}`,
  ];

  return `${lines.join("\n").trim()}\n`;
}

export async function POST(req: NextRequest) {
  try {
    const body = (await req.json()) as SavePayload;
    const title = safeTitle(text(body.title));
    const content = text(body.content);
    const rawType = text(body.type);

    if (!title) {
      return NextResponse.json({ error: "title wajib diisi" }, { status: 400 });
    }

    if (!content || content.length < 20) {
      return NextResponse.json({ error: "content dokumen terlalu pendek/kosong" }, { status: 400 });
    }

    if (rawType && !isDocumentType(rawType)) {
      return NextResponse.json({ error: "type dokumen tidak valid" }, { status: 400 });
    }

    const auth = getAuth();
    const docs = google.docs({ version: "v1", auth });
    const drive = google.drive({ version: "v3", auth });
    const docTitle = `systemswi - ${title}`;

    const created = await docs.documents.create({
      requestBody: { title: docTitle },
    });
    const documentId = created.data.documentId;

    if (!documentId) {
      return NextResponse.json({ error: "Gagal membuat Google Doc" }, { status: 500 });
    }

    const googleDocText = buildGoogleDocText({
      title,
      content,
      id: body.id,
      type: body.type,
      letterNumber: body.letterNumber,
    });

    await docs.documents.batchUpdate({
      documentId,
      requestBody: {
        requests: [
          {
            insertText: {
              location: { index: 1 },
              text: googleDocText,
            },
          },
        ],
      },
    });

    const file = await drive.files.get({
      fileId: documentId,
      fields: "id,name,webViewLink,createdTime",
    });

    const audit = await appendSwiMemoryLog({
      action: "Document Save",
      target: `Google Docs:${documentId}`,
      summary: `systemswi saved ${rawType || "document"} draft \"${title}\" from Document Generator.`,
    }).catch((error) => ({ error: String(error) }));

    return NextResponse.json(
      {
        success: true,
        source: "Google Docs + SWI Memory Log",
        document: {
          id: body.id || `doc-${Date.now()}`,
          type: body.type,
          title,
          driveFileId: documentId,
          driveUrl: file.data.webViewLink,
          createdAt: file.data.createdTime || new Date().toISOString(),
        },
        audit,
      },
      { status: 201 },
    );
  } catch (error) {
    if (isGoogleWorkspaceAuthError(error)) {
      return NextResponse.json(
        {
          error: "Google Workspace perlu re-auth sebelum dokumen bisa disimpan",
          ...googleWorkspaceWriteBlockedSource("Google Docs + SWI Memory Log", error),
        },
        { status: 503 },
      );
    }

    return NextResponse.json({ error: "Gagal simpan dokumen ke Google Docs", details: String(error) }, { status: 500 });
  }
}
