// Seed data for Expense Approval Flow
import type { ExpenseSubmission, ExpenseApprover } from "./types";

export const seedApprovers: ExpenseApprover[] = [
  {
    id: "apr-001",
    name: "Beriman Juliano",
    role: "Direktur",
    email: "beriman@sensasiwangi.id",
  },
];

export const seedSubmissions: ExpenseSubmission[] = [
  {
    id: "exp-001",
    date: "2026-06-15",
    submitterName: "Wapiq Rizya Zaelan",
    relatedEvent: "Fragrantions 2026",
    category: "marketing",
    description: "Pembuatan banner Instagram untuk Road to Fragrantions",
    amount: 750000,
    proofUrl: "",
    status: "approved",
    reviewedBy: "Beriman Juliano",
    reviewedDate: "2026-06-16",
    notes: "Disetujui — sudah sesuai budget marketing",
  },
  {
    id: "exp-002",
    date: "2026-06-18",
    submitterName: "Beriman Juliano",
    relatedEvent: "Fragrantions 2026",
    category: "logistics",
    description: "Ongkir pengiriman merchandise SWI ke venue expo",
    amount: 1250000,
    proofUrl: "",
    status: "approved",
    reviewedBy: "Beriman Juliano",
    reviewedDate: "2026-06-18",
    notes: "Self-approved sebagai Direktur",
  },
  {
    id: "exp-003",
    date: "2026-06-20",
    submitterName: "Wapiq Rizya Zaelan",
    relatedEvent: "Fragrantions 2026",
    category: "venue",
    description: "DP booking venue Jakarta Convention Center",
    amount: 50000000,
    proofUrl: "",
    status: "pending",
    reviewedBy: "",
    reviewedDate: "",
    notes: "",
  },
  {
    id: "exp-004",
    date: "2026-06-19",
    submitterName: "Tim Produksi",
    relatedEvent: "SWI Store TIM",
    category: "equipment",
    description: "Pembelian perlengkapan produksi parfum batch #007",
    amount: 3200000,
    proofUrl: "",
    status: "pending",
    reviewedBy: "",
    reviewedDate: "",
    notes: "",
  },
  {
    id: "exp-005",
    date: "2026-06-17",
    submitterName: "Beriman Juliano",
    relatedEvent: "SWI Store TIM",
    category: "consumption",
    description: "Konsumsi rapat bulanan divisi Store",
    amount: 450000,
    proofUrl: "",
    status: "rejected",
    reviewedBy: "Beriman Juliano",
    reviewedDate: "2026-06-18",
    notes: "Ditolak — bukan prioritas bulan ini",
  },
];
