// Document templates
import type { DocumentTemplate, DocumentType } from "./types";

export const DOCUMENT_TEMPLATES: DocumentTemplate[] = [
    {
        id: "tpl-invoice",
        type: "invoice",
        name: "Invoice Tenant/Sponsor",
        description: "Invoice pembayaran booth, sponsor, atau layanan event dengan status jatuh tempo",
        icon: "🧾",
        fields: [
            { id: "bill_to", label: "Ditagihkan Kepada", type: "text", required: true, placeholder: "Nama tenant/sponsor" },
            { id: "invoice_number", label: "Nomor Invoice", type: "text", placeholder: "Kosongkan untuk auto-generate" },
            { id: "event_name", label: "Nama Event", type: "text", required: true, placeholder: "Fragrantions 2026" },
            { id: "description", label: "Deskripsi Tagihan", type: "textarea", required: true, placeholder: "Booth package / sponsorship tier / service" },
            { id: "amount", label: "Nilai Tagihan (Rp)", type: "number", required: true },
            { id: "paid_amount", label: "Sudah Dibayar (Rp)", type: "number" },
            { id: "due_date", label: "Jatuh Tempo", type: "date", required: true },
            { id: "payment_terms", label: "Termin Pembayaran", type: "textarea", placeholder: "DP 50%, pelunasan H-14" },
            { id: "notes", label: "Catatan / Proof URL", type: "textarea" },
        ],
    },
    {
        id: "tpl-sponsor-proposal",
        type: "sponsor_proposal",
        name: "Proposal Sponsor",
        description: "Proposal kemitraan sponsor Fragrantions dengan tier benefit dan deliverables",
        icon: "🤝",
        fields: [
            { id: "sponsor_name", label: "Nama Sponsor", type: "text", required: true },
            { id: "event_name", label: "Nama Event", type: "text", required: true, placeholder: "Fragrantions 2026" },
            { id: "tier", label: "Tier", type: "select", required: true, options: [
                { value: "platinum", label: "Platinum" },
                { value: "gold", label: "Gold" },
                { value: "silver", label: "Silver" },
                { value: "bronze", label: "Bronze" },
                { value: "media", label: "Media Partner" },
                { value: "community", label: "Community Partner" },
            ] },
            { id: "sponsorship_amount", label: "Nilai Sponsorship (Rp)", type: "number" },
            { id: "objective", label: "Tujuan Kerja Sama", type: "textarea" },
            { id: "deliverables", label: "Deliverables", type: "textarea", placeholder: "Logo placement, booth, stage mention, konten IG, dll." },
            { id: "contact_person", label: "Contact Person", type: "text" },
        ],
    },
    {
        id: "tpl-tenant-agreement",
        type: "tenant_agreement",
        name: "Tenant Agreement",
        description: "Draft kesepakatan tenant: booth, biaya, aturan operasional, dan deliverables",
        icon: "🏪",
        fields: [
            { id: "tenant_name", label: "Nama Tenant/Brand", type: "text", required: true },
            { id: "event_name", label: "Nama Event", type: "text", required: true, placeholder: "Fragrantions 2026" },
            { id: "booth_number", label: "Nomor Booth", type: "text", placeholder: "TBA" },
            { id: "package_type", label: "Paket", type: "text", placeholder: "Standard / Premium / F&B" },
            { id: "fee", label: "Biaya Tenant (Rp)", type: "number", required: true },
            { id: "payment_status", label: "Status Pembayaran", type: "select", options: [
                { value: "prospect", label: "Prospect" },
                { value: "invoice-sent", label: "Invoice Sent" },
                { value: "partial", label: "Partial" },
                { value: "paid", label: "Paid" },
            ] },
            { id: "operational_rules", label: "Aturan Operasional", type: "textarea" },
            { id: "notes", label: "Catatan", type: "textarea" },
        ],
    },
    {
        id: "tpl-proposal",
        type: "proposal",
        name: "Proposal Event",
        description: "Template proposal untuk pengajuan event",
        icon: "📝",
        fields: [
            { id: "event_name", label: "Nama Event", type: "text", required: true },
            { id: "event_date", label: "Tanggal Event", type: "date", required: true },
            { id: "location", label: "Lokasi", type: "text", required: true },
            { id: "background", label: "Latar Belakang", type: "textarea", required: true },
            { id: "objectives", label: "Tujuan Event", type: "textarea", required: true },
            { id: "target_audience", label: "Target Audience", type: "text" },
            { id: "estimated_budget", label: "Estimasi Budget (Rp)", type: "number" },
        ],
    },
    {
        id: "tpl-rab",
        type: "rab",
        name: "Rencana Anggaran Biaya",
        description: "Template RAB untuk perencanaan budget event",
        icon: "💰",
        fields: [
            { id: "event", label: "Pilih Event", type: "event", required: true },
            { id: "period", label: "Periode", type: "text" },
            { id: "notes", label: "Catatan", type: "textarea" },
        ],
    },
    {
        id: "tpl-event-closeout-report",
        type: "event_closeout_report",
        name: "Event Closeout Report",
        description: "Laporan penutupan event: budget vs actual, revenue tenant/sponsor, payable/receivable, dokumentasi, dan lessons learned berbasis Sheets",
        icon: "✅",
        fields: [
            { id: "event", label: "Pilih Event", type: "event", required: true },
            { id: "period", label: "Periode", type: "text", placeholder: "Juli 2026" },
            { id: "documentation_url", label: "Link Dokumentasi / Drive", type: "text", placeholder: "TBA jika belum ada" },
            { id: "lessons_learned", label: "Lessons Learned", type: "textarea", placeholder: "Catatan panitia setelah event" },
            { id: "next_actions", label: "Next Actions", type: "textarea" },
        ],
    },
    {
        id: "tpl-lapkeu",
        type: "laporan_keuangan",
        name: "Laporan Keuangan",
        description: "Template laporan keuangan event",
        icon: "📊",
        fields: [
            { id: "event", label: "Pilih Event", type: "event", required: true },
            { id: "period_start", label: "Periode Mulai", type: "date", required: true },
            { id: "period_end", label: "Periode Akhir", type: "date", required: true },
            { id: "summary", label: "Ringkasan", type: "textarea" },
        ],
    },
    {
        id: "tpl-monthly-gcg-report",
        type: "monthly_gcg_report",
        name: "Monthly GCG Report",
        description: "Laporan TARIF/GCG bulanan: expense proof, audit trail, shareholder debt, compliance, vendor COI, dan exceptions dari Google Sheets",
        icon: "⚖️",
        fields: [
            { id: "period", label: "Periode", type: "text", required: true, placeholder: "Juli 2026" },
            { id: "director_notes", label: "Catatan Direksi", type: "textarea" },
            { id: "follow_up", label: "Follow-up / Keputusan", type: "textarea" },
        ],
    },
    {
        id: "tpl-monthly-report",
        type: "monthly_report",
        name: "Monthly Report",
        description: "Ringkasan bulanan finance + event + inventory untuk direksi",
        icon: "📅",
        fields: [
            { id: "period", label: "Periode", type: "text", required: true, placeholder: "Juni 2026" },
            { id: "executive_summary", label: "Executive Summary", type: "textarea" },
            { id: "finance_notes", label: "Catatan Finance", type: "textarea" },
            { id: "event_notes", label: "Catatan Event", type: "textarea" },
            { id: "inventory_notes", label: "Catatan Inventory/Procurement", type: "textarea" },
            { id: "next_actions", label: "Next Actions", type: "textarea" },
        ],
    },
    {
        id: "tpl-progress",
        type: "laporan_progress",
        name: "Laporan Progress",
        description: "Template laporan progress event",
        icon: "📈",
        fields: [
            { id: "event", label: "Pilih Event", type: "event", required: true },
            { id: "report_date", label: "Tanggal Laporan", type: "date", required: true },
            { id: "achievements", label: "Pencapaian", type: "textarea" },
            { id: "challenges", label: "Kendala", type: "textarea" },
            { id: "next_steps", label: "Rencana Selanjutnya", type: "textarea" },
        ],
    },
    {
        id: "tpl-undangan",
        type: "surat_undangan",
        name: "Surat Undangan",
        description: "Template surat undangan resmi",
        icon: "✉️",
        fields: [
            { id: "recipient_name", label: "Nama Penerima", type: "text", required: true },
            { id: "recipient_title", label: "Jabatan Penerima", type: "text" },
            { id: "event_name", label: "Nama Event", type: "text", required: true },
            { id: "event_date", label: "Tanggal Event", type: "date", required: true },
            { id: "event_time", label: "Waktu", type: "text" },
            { id: "location", label: "Lokasi", type: "text", required: true },
            { id: "dress_code", label: "Dress Code", type: "text" },
        ],
    },
    {
        id: "tpl-kontrak",
        type: "kontrak",
        name: "Kontrak Kerjasama",
        description: "Template kontrak kerjasama dengan vendor",
        icon: "📄",
        fields: [
            { id: "party_1", label: "Pihak Pertama", type: "text", required: true },
            { id: "party_2", label: "Pihak Kedua", type: "text", required: true },
            { id: "scope", label: "Ruang Lingkup Kerjasama", type: "textarea", required: true },
            { id: "value", label: "Nilai Kontrak (Rp)", type: "number", required: true },
            { id: "start_date", label: "Tanggal Mulai", type: "date", required: true },
            { id: "end_date", label: "Tanggal Berakhir", type: "date", required: true },
            { id: "terms", label: "Syarat & Ketentuan", type: "textarea" },
        ],
    },
    {
        id: "tpl-tugas",
        type: "surat_tugas",
        name: "Surat Tugas",
        description: "Template surat tugas untuk panitia",
        icon: "📋",
        fields: [
            { id: "employee_name", label: "Nama Karyawan", type: "text", required: true },
            { id: "employee_role", label: "Jabatan", type: "text", required: true },
            { id: "assignment", label: "Penugasan", type: "textarea", required: true },
            { id: "start_date", label: "Tanggal Mulai", type: "date", required: true },
            { id: "end_date", label: "Tanggal Selesai", type: "date" },
            { id: "location", label: "Lokasi Tugas", type: "text" },
        ],
    },
    {
        id: "tpl-notulen",
        type: "notulen",
        name: "Notulen Rapat",
        description: "Template notulen rapat",
        icon: "📝",
        fields: [
            { id: "meeting_title", label: "Judul Rapat", type: "text", required: true },
            { id: "meeting_date", label: "Tanggal Rapat", type: "date", required: true },
            { id: "attendees", label: "Peserta Rapat", type: "textarea", required: true },
            { id: "agenda", label: "Agenda", type: "textarea", required: true },
            { id: "discussion", label: "Pembahasan", type: "textarea", required: true },
            { id: "decisions", label: "Keputusan", type: "textarea" },
            { id: "action_items", label: "Tindak Lanjut", type: "textarea" },
        ],
    },
];

// Get template by type
export function getTemplateByType(type: DocumentType): DocumentTemplate | undefined {
    return DOCUMENT_TEMPLATES.find((t) => t.type === type);
}

// Get all templates
export function getAllTemplates(): DocumentTemplate[] {
    return DOCUMENT_TEMPLATES;
}
